// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfr2XxptDBiafkkk2VpGy5ShKlfzLXqRk',
    appId: '1:575623197908:web:a002581d7be8cffe137741',
    messagingSenderId: '575623197908',
    projectId: 'flowfinance-9d521',
    authDomain: 'flowfinance-9d521.firebaseapp.com',
    storageBucket: 'flowfinance-9d521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mEtfal2cYJpDsMpUPx2HBDsDNdDdd1g',
    appId: '1:575623197908:android:9f098a748ed20bfc137741',
    messagingSenderId: '575623197908',
    projectId: 'flowfinance-9d521',
    storageBucket: 'flowfinance-9d521.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfr2XxptDBiafkkk2VpGy5ShKlfzLXqRk',
    appId: '1:575623197908:web:40439c1ae15be1bf137741',
    messagingSenderId: '575623197908',
    projectId: 'flowfinance-9d521',
    authDomain: 'flowfinance-9d521.firebaseapp.com',
    storageBucket: 'flowfinance-9d521.firebasestorage.app',
  );
}
